[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Estruturas de Madeira"
authors = [{name = "Paulo Mappa", email = "paulomappa@cefetmg.br"}]
dynamic = ["version", "description"]
